#!/bin/bash

set -eu

image=$1

if [ -f $image ]; then
    exit 0
fi
path=$(mktemp --directory lxdapi.busybox.XXXXXXXX)
arch=$(uname --machine)

mkdir -p $path/rootfs/{bin,dev,etc,mnt,proc,root,sbin,sys,tmp,usr/sbin,usr/bin}

# Add an /etc/inittab; this is to work around:
# http://lists.busybox.net/pipermail/busybox/2015-November/083618.html
# Basically, since there are some hardcoded defaults that misbehave, we
# just pass an empty inittab so those aren't applied, and then busybox
# doesn't spin forever.
echo > $path/rootfs/etc/inittab

cat > $path/metadata.yaml <<EOF
architecture: $arch
creation_date: $(date +%s)
properties:
    os: Busybox
    architecture: $arch
    description: Busybox $arch
    name: Busybox-$arch
EOF

cp $(which busybox) $path/rootfs/bin
for i in $($path/rootfs/bin/busybox --list-install); do
    ln -sfn /bin/busybox "$path/rootfs/$i"
done

pushd $path
tar cvJf $image *
popd
rm -rf $path
